@startuml Magnolia-Digi

participant TargetDevice
participant "Entitlement Server" as ES
participant "Carrier IT(CSG)" as CSG

TargetDevice -> ES: getAuthentication (auth-type=“token”, subscriber-id=<src-device-imsi@NAI>,transfer-token)\nenablePushNotification (old-imsi, profile-released)\ntransferSIMService (source-device, target-device)
note over ES,SMDP: Reserve new ICCID for target device from SM_DP+

ES -> CSG: SubmitSwapSimOrderRequest [CorrelationId,msisdn,newICCID]
ES -> ES: SubmitSwapSimOrderResponse [timeout]
ES -> TargetDevice: enablePushNotification[6100]\ntransferSIMService (status=6005)

@enduml